version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Run docker containers
          command: |
            cd ci
            docker-compose up -d
      - run:
          name: Run Test Script
          command: |
            while [ "$(docker inspect -f '{{.State.Running}}' tester)" == "true" ]; do
              echo "Waiting for tests to complete..."
              sleep 1
            done
            grep -Eq "FAIL|ERROR" tests/out.txt && exit 1 || exit 0
      - store_artifacts:
          path: test_output.log
          destination: test_output.log

workflows:
  version: 2
  test:
    jobs:
      - test
